### ISSUE TITLE
Pointer precision loss casting pointer down to (int

### ISSUE THREAD

**Issue by johnphamngc** [nasa/SC#1]
Pointer precision loss casting pointer down to (int), causing segfault on 64-bit. See:

https://github.com/nasa/SC/blob/43392d75418998a75f04b64416a3323be1d51918/fsw/src/sc_rtsrq.c#L641

**Comment by ejtimmon** [comment]
Thanks for reporting.  This will be fixed in the next release.

**Comment by skliper** [comment]
Fixed in ae2d615e7431d430950fd25ccc7e85587c03ad95 bulk update.
